# Generated by Django 4.1.1 on 2024-01-09 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0050_alter_ipvisit_admissiondate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security_release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateRaised', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('totalpaid', models.FloatField(max_length=50)),
                ('totalbill', models.FloatField(max_length=50)),
                ('releasedate', models.DateTimeField(null=True)),
                ('nokname', models.CharField(max_length=200, null=True)),
                ('nokid', models.CharField(max_length=50, null=True)),
                ('nokphone', models.CharField(max_length=50, null=True)),
                ('nokrelation', models.CharField(max_length=50, null=True)),
                ('patientno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata')),
                ('paymode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.schemes')),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='raised_by', to=settings.AUTH_USER_MODEL)),
                ('releasedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='release_by', to=settings.AUTH_USER_MODEL)),
                ('visitNoIp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit')),
            ],
        ),
    ]
