# Generated by Django 4.1.1 on 2023-01-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmdispense',
            old_name='op_number',
            new_name='patnumber',
        ),
        migrations.AlterField(
            model_name='pharmdispense',
            name='DispenseDate',
            field=models.DateField(null=True),
        ),
    ]
