# Generated by Django 4.1.1 on 2023-01-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_rename_op_number_pharmdispense_patnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmdispense',
            name='days',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmdispense',
            name='dosage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pharmdispense',
            name='frequency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
