# Generated by Django 4.1.1 on 2023-01-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_pharmdispense_days_alter_pharmdispense_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmdispense',
            name='DispenseDate',
            field=models.DateTimeField(null=True),
        ),
    ]
