# Generated by Django 4.1.1 on 2022-12-20 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0003_remove_patientbill_op_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('ref_number', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('patient_type', models.CharField(max_length=50, null=True)),
                ('paymode', models.CharField(max_length=50, null=True)),
                ('bill_point', models.CharField(max_length=50, null=True)),
                ('urgency', models.CharField(default='normal', max_length=50, null=True)),
                ('quantity', models.FloatField()),
                ('total_price', models.FloatField()),
                ('pay_status', models.CharField(max_length=50, null=True)),
                ('receipt_no', models.IntegerField(null=True)),
                ('invoice_no', models.IntegerField(null=True)),
                ('billType', models.CharField(default='normal', max_length=50)),
                ('op_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.PatientBioData')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.services')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('visitNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.opvisits')),
            ],
        ),
        migrations.CreateModel(
            name='cashDeposit',
            fields=[
                ('reffNumber', models.AutoField(primary_key=True, serialize=False)),
                ('depositAmount', models.FloatField()),
                ('visitNoOp', models.IntegerField()),
                ('visitNoIp', models.IntegerField()),
                ('balance', models.FloatField()),
                ('billReferenceNoIp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit')),
                ('billReferenceNoOp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits')),
                ('patientType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patienttype')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
