# Generated by Django 4.1.1 on 2022-12-20 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cashierReceipt',
            fields=[
                ('trans_number', models.AutoField(primary_key=True, serialize=False)),
                ('trans_date', models.DateField(auto_now_add=True)),
                ('receipt_no', models.CharField(max_length=200)),
                ('paid_amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='billType',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='receipt_no',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='staff',
        ),
        migrations.AddField(
            model_name='patientbill',
            name='billed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='svs_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='waiver',
            fields=[
                ('waiverNo', models.AutoField(primary_key=True, serialize=False)),
                ('waiver_date', models.DateField(auto_now_add=True)),
                ('waiver_amount', models.FloatField(null=True)),
                ('waiver_status', models.CharField(max_length=20)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashier', to=settings.AUTH_USER_MODEL)),
                ('receipt_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.cashierreceipt')),
                ('serviceReffNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill')),
                ('waived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='waivedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patientInvoice',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100, null=True)),
                ('service_invoice_price', models.FloatField()),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_settled_by', to=settings.AUTH_USER_MODEL)),
                ('serviceReffNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill')),
            ],
        ),
        migrations.CreateModel(
            name='cashierShift',
            fields=[
                ('shiftNo', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('shift_status', models.CharField(max_length=20)),
                ('close_date', models.DateTimeField(null=True)),
                ('cashier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cashierreceipt',
            name='service_reff_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill'),
        ),
        migrations.AddField(
            model_name='cashierreceipt',
            name='shift_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.cashiershift'),
        ),
        migrations.CreateModel(
            name='bill_adjustment',
            fields=[
                ('trans_no', models.AutoField(primary_key=True, serialize=False)),
                ('adj_amount', models.FloatField()),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('service_reff_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill')),
                ('trans_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
