# Generated by Django 4.1.1 on 2023-01-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_rename_service_reff_no_cashierreceipt_billreffno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='DepositDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
