# Generated by Django 4.1.1 on 2023-01-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_cashdeposit_depositdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierreceipt',
            name='mobile_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashierreceipt',
            name='mobile_trans_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cashierreceipt',
            name='paymode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cashierreceipt',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
