# Generated by Django 4.1.1 on 2023-01-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_cashierreceipt_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiershift',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cashiershift',
            name='start_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cashiershift',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
