# Generated by Django 4.1.1 on 2023-01-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0010_alter_theatre_capacity'),
        ('finance', '0006_cashiershift_close_time_cashiershift_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_adjustment',
            name='pat_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.AddField(
            model_name='cashdeposit',
            name='pat_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.AddField(
            model_name='cashierreceipt',
            name='pat_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.AddField(
            model_name='patientinvoice',
            name='pat_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='pat_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
    ]
