# Generated by Django 4.1.1 on 2023-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_bill_adjustment_pat_card_cashdeposit_pat_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierreceipt',
            name='receipt_no',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
