# Generated by Django 4.1.1 on 2023-01-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_cashierreceipt_receipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierreceipt',
            name='receipt_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
