# Generated by Django 4.1.1 on 2023-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_cashierreceipt_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierreceipt',
            name='receipt_status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
