# Generated by Django 4.1.1 on 2023-01-08 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_cashierreceipt_receipt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashierreceipt',
            name='receipt_status',
        ),
    ]
