# Generated by Django 4.1.1 on 2023-02-27 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_substoreitem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_patientbill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='done_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='done_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store'),
        ),
    ]
