# Generated by Django 4.1.1 on 2023-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_patientbill_done_by_patientbill_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='invoice_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientbill',
            name='pay_status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
