# Generated by Django 4.1.1 on 2023-04-17 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0014_patientbill_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='invoice_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='invoice_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
