# Generated by Django 4.1.1 on 2023-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_patientbill_invoice_by_patientbill_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='wlknumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
