# Generated by Django 4.1.1 on 2023-07-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_patientbill_request_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierreceipt',
            name='receipt_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
