# Generated by Django 4.1.1 on 2023-09-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0001_initial'),
        ('finance', '0018_cashierreceipt_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='farewell_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farewell.farewellregister'),
        ),
    ]
