# Generated by Django 4.1.1 on 2023-10-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_cashdeposit_billreferencenoip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiver',
            name='transaction_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
