# Generated by Django 4.1.1 on 2023-10-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_waiver_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashierreceipt',
            name='trans_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
