# Generated by Django 4.1.1 on 2023-10-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_cashierreceipt_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiver',
            name='receipt_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
