# Generated by Django 4.1.1 on 2023-10-04 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0039_opvisits_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0024_alter_waiver_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiver',
            name='vno_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit'),
        ),
        migrations.AddField(
            model_name='waiver',
            name='vno_op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits'),
        ),
        migrations.CreateModel(
            name='waiverNotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=500, null=True)),
                ('notes_date', models.DateTimeField(auto_now_add=True)),
                ('notes_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='waiver',
            name='notesid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.waivernotes'),
        ),
    ]
