# Generated by Django 4.1.1 on 2023-10-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0026_cashierreceipt_cancel_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashierreceipt',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='cashierreceipt',
            name='cancelled_by',
        ),
        migrations.CreateModel(
            name='receipt_cancel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cancelled_on', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=50, null=True)),
                ('cancel_reason', models.CharField(max_length=250, null=True)),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancelled_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
