# Generated by Django 4.1.1 on 2023-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_mpesaresponsebody_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='waivernotes',
            name='patient_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
