# Generated by Django 4.1.1 on 2023-11-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0040_ipvisit_patientcategory'),
        ('finance', '0029_waivernotes_patient_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waivernotes',
            name='patient_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
    ]
