# Generated by Django 4.1.1 on 2024-01-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_patientbill_quantity_patientbill_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preauth_invoice',
            old_name='status',
            new_name='preauth_status',
        ),
        migrations.RenameField(
            model_name='preauth_invoice',
            old_name='quantity',
            new_name='quant',
        ),
        migrations.RenameField(
            model_name='preauth_invoice',
            old_name='total_price',
            new_name='totalprice',
        ),
    ]
