# Generated by Django 4.1.1 on 2024-01-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0034_invoice_preauth_delete_preauth_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='invoice_preauth',
        ),
    ]
