# Generated by Django 4.1.1 on 2022-10-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0003_customuser_nationaidno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nationaIdNo',
            new_name='national_Id_No',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='usertype',
            new_name='user_type',
        ),
    ]
