# Generated by Django 4.1.1 on 2022-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0004_rename_nationaidno_customuser_national_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('medical records', 'medical records'), ('consultation', 'consultation'), ('nursing', 'nursing'), ('finance', 'finance'), ('laboratory', 'laboratory'), ('radiology', 'radiology'), ('pharmacy', 'pharmacy'), ('stores', 'stores'), ('Administration', 'Administration')], max_length=100),
        ),
    ]
