# Generated by Django 4.1.1 on 2023-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemusers', '0005_alter_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('medical_records', 'medical_records'), ('consultation', 'consultation'), ('nursing', 'nursing'), ('finance', 'finance'), ('laboratory', 'laboratory'), ('radiology', 'radiology'), ('pharmacy', 'pharmacy'), ('stores', 'stores'), ('farewell', 'farewell'), ('Security', 'Security'), ('Human_resource', 'Human_resource'), ('Public_health', 'Public_health'), ('Administration', 'Administration')], max_length=100),
        ),
    ]
