# Generated by Django 4.1.1 on 2022-10-03 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('exam_no', models.AutoField(primary_key=True, serialize=False)),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('receive_time', models.TimeField(auto_now_add=True)),
                ('exam_notes', models.TextField()),
                ('exam_notes_date', models.DateField(null=True)),
                ('exam_notes_time', models.TimeField(null=True)),
                ('exam_status', models.CharField(max_length=100)),
                ('notes_by', models.CharField(max_length=100)),
                ('op_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.PatientBioData')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('request_reff_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbill')),
                ('request_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.services')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMiss',
            fields=[
                ('miss_number', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('request_reff_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbill')),
            ],
        ),
    ]
