# Generated by Django 4.1.1 on 2022-12-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammiss',
            name='request_reff_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='request_reff_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finance.patientbill'),
        ),
    ]
