# Generated by Django 4.1.1 on 2023-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_alter_exammiss_request_reff_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='VisitNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
