# Generated by Django 4.1.1 on 2023-01-26 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiology', '0003_examresult_visitno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='notes_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='radiologist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionist', to=settings.AUTH_USER_MODEL),
        ),
    ]
