# Generated by Django 4.1.1 on 2023-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_alter_examresult_notes_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='radtech',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
