# Generated by Django 4.1.1 on 2023-12-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_examresult_radtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='uuid_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
