# Generated by Django 4.1.1 on 2024-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0007_examnotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam_notes',
            field=models.TextField(null=True),
        ),
    ]
