# Generated by Django 4.1.1 on 2023-01-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_druggeneralitem_itemdescp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substoreitem',
            name='batchNo',
        ),
    ]
