# Generated by Django 4.1.1 on 2023-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_substoreitem_batchno'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='item_category',
            field=models.CharField(choices=[('DRUG', 'DRUG'), ('NON-PHARM', 'NON-PHARM')], max_length=50, null=True),
        ),
    ]
