# Generated by Django 4.1.1 on 2023-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='storeHead',
            new_name='storeManager',
        ),
        migrations.AlterField(
            model_name='druggeneralitem',
            name='itemType',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mainstoreitems',
            name='itemCategory',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_category',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplyItem',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
