# Generated by Django 4.1.1 on 2023-01-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_status_alter_store_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='servePoint',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('External facilities', 'External facilities'), ('All', 'All')], max_length=20, null=True),
        ),
    ]
