# Generated by Django 4.1.1 on 2023-01-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_store_servepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='order_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
