# Generated by Django 4.1.1 on 2023-01-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_itemorder_ordertype_alter_itemorder_issuedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='urgency',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
