# Generated by Django 4.1.1 on 2023-01-31 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0011_itemorder_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='issueTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issueto', to=settings.AUTH_USER_MODEL),
        ),
    ]
