# Generated by Django 4.1.1 on 2023-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_itemorder_issueto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='issueTo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
