# Generated by Django 4.1.1 on 2023-02-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_itemorder_issueto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='druggeneralitem',
            name='itemType',
        ),
        migrations.AlterField(
            model_name='druggeneralitem',
            name='itemCategory',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both')], max_length=50, null=True),
        ),
    ]
