# Generated by Django 4.1.1 on 2023-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_druggeneralitem_itemdescp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substoreitem',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
