# Generated by Django 4.1.1 on 2023-02-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_substoreitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='purpose',
            field=models.CharField(choices=[('nursing', 'nursing'), ('pharmacy', 'pharmacy')], max_length=20, null=True),
        ),
    ]
