# Generated by Django 4.1.1 on 2023-03-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_store_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druggeneralitem',
            name='itemCategory',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both'), ('Laboratory', 'Laboratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mainstoreitems',
            name='itemCategory',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both'), ('Laboratory', 'Laboratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='item_category',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both'), ('Laboratory', 'Laboratory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplyItem',
            field=models.CharField(choices=[('Pharmaceuticals', 'Pharmaceuticals'), ('Non-Pharmaceuticals', 'Non-Pharmaceuticals'), ('Both', 'Both'), ('Laboratory', 'Laboratory')], max_length=100, null=True),
        ),
    ]
