# Generated by Django 4.1.1 on 2023-12-23 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0019_storedelivery_inspector_storedelivery_lpono'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReconciliation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reconcile_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(null=True)),
                ('itname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.druggeneralitem')),
                ('reconcileBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reconcileby', to=settings.AUTH_USER_MODEL)),
                ('storename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store')),
            ],
        ),
    ]
