# Generated by Django 4.1.1 on 2023-03-31 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalRecords', '0020_opvisits_invoice_no'),
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='visitno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='op_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
