# Generated by Django 4.1.1 on 2023-04-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0021_alter_ipvisit_admstatus'),
        ('nursing', '0002_triage_visitno_alter_triage_op_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='ipvisitno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit'),
        ),
    ]
