# Generated by Django 4.1.1 on 2023-04-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0003_triage_ipvisitno'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='urgency',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
