# Generated by Django 4.1.1 on 2023-07-12 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0037_schemes_limit_per_visit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing', '0004_triage_urgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardex',
            fields=[
                ('reffNo', models.AutoField(primary_key=True, serialize=False)),
                ('cardexDate', models.DateField(null=True)),
                ('cardexTime', models.TimeField(null=True)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('recordDate', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('patNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata')),
                ('visitNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit')),
            ],
        ),
    ]
