# Generated by Django 4.1.1 on 2023-07-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0005_cardex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardex',
            name='cardexDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cardex',
            name='cardexTime',
            field=models.TimeField(),
        ),
    ]
