# Generated by Django 4.1.1 on 2023-07-13 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing', '0006_alter_cardex_cardexdate_alter_cardex_cardextime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardex',
            name='editDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cardex',
            name='editedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='editby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardex',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
