# Generated by Django 4.1.1 on 2023-12-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0007_cardex_editdate_cardex_editedby_alter_cardex_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='blood_oxygen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='muac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='blood_pressure',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='pulse_rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
