# Generated by Django 4.1.1 on 2023-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0008_triage_blood_oxygen_triage_muac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='pat_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
