# Generated by Django 4.1.1 on 2024-01-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0009_triage_pat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='nurse_notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
