# Generated by Django 4.1.1 on 2022-10-03 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('param_no', models.AutoField(primary_key=True, serialize=False)),
                ('param_name', models.CharField(max_length=100, null=True)),
                ('lower_limit', models.CharField(max_length=100, null=True)),
                ('upper_limit', models.CharField(max_length=100, null=True)),
                ('value_units', models.CharField(max_length=100, null=True)),
                ('posible_result', models.TextField(null=True)),
                ('param_type', models.CharField(max_length=100, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('test_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.services')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('result_no', models.AutoField(primary_key=True, serialize=False)),
                ('receive_date', models.DateField(auto_now_add=True)),
                ('receive_time', models.TimeField(auto_now_add=True)),
                ('result_value', models.JSONField(default=dict)),
                ('testComment', models.CharField(max_length=255, null=True)),
                ('editReason', models.CharField(max_length=255, null=True)),
                ('results_date', models.DateField(null=True)),
                ('results_time', models.TimeField(null=True)),
                ('exam_status', models.CharField(max_length=100, null=True)),
                ('performed_by', models.CharField(max_length=255, null=True)),
                ('confirmed_by', models.CharField(max_length=255, null=True)),
                ('op_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.PatientBioData')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('request_reff_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbill')),
                ('request_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.services')),
            ],
        ),
        migrations.CreateModel(
            name='LabMissTest',
            fields=[
                ('miss_number', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('request_reff_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbill')),
            ],
        ),
    ]
