# Generated by Django 4.1.1 on 2022-10-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='sampleNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='confirmed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='performedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receivedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
