# Generated by Django 4.1.1 on 2022-10-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0003_labresult_requestedit_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='labDepartment',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
