# Generated by Django 4.1.1 on 2022-10-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laboratory', '0004_labdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='labItemRequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestDate', models.DateField(null=True)),
                ('requestQuant', models.FloatField(null=True)),
                ('issueQuant', models.FloatField(null=True)),
                ('issueDate', models.DateField(null=True)),
                ('bench', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratory.labdepartment')),
                ('issuedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issby', to=settings.AUTH_USER_MODEL)),
                ('itemCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.druggeneralitem')),
                ('requestBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rqby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
