# Generated by Django 4.1.1 on 2022-12-20 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_labmisstest_request_reff_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmisstest',
            name='request_reff_no',
        ),
    ]
