# Generated by Django 4.1.1 on 2023-01-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0009_labdepartmenttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='VisitNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
