# Generated by Django 4.1.1 on 2023-05-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0010_labresult_visitno'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestparameter',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
