# Generated by Django 4.1.1 on 2023-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0011_labtestparameter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdepartment',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
