# Generated by Django 4.1.1 on 2023-01-03 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='facility',
            fields=[
                ('facilityid', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateField(auto_now_add=True, null=True)),
                ('facName', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('phoneNo', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('stmtHeader', models.CharField(max_length=200, null=True)),
                ('stmtFooter', models.CharField(max_length=200, null=True)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
