# Generated by Django 4.1.1 on 2023-01-09 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysadmin', '0002_facility_facabbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='facdepartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(auto_now_add=True, null=True)),
                ('deptName', models.CharField(max_length=100, null=True)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
