# Generated by Django 4.1.1 on 2023-02-22 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysadmin', '0003_facdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(auto_now_add=True, null=True)),
                ('stationName', models.CharField(max_length=100, null=True)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
