# Generated by Django 4.1.1 on 2023-06-07 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MedicalRecords', '0035_alter_patientbiodata_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='farewellRegister',
            fields=[
                ('registerDate', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BodyID', models.CharField(max_length=100, null=True)),
                ('tagNo', models.CharField(max_length=100, null=True)),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('dcIdno', models.PositiveIntegerField(null=True)),
                ('dcAge', models.PositiveIntegerField(null=True)),
                ('dcGender', models.CharField(max_length=20, null=True)),
                ('dcResidence', models.CharField(max_length=100, null=True)),
                ('nokName', models.CharField(max_length=200, null=True)),
                ('nokPhone', models.PositiveIntegerField(null=True)),
                ('nokId', models.PositiveIntegerField(null=True)),
                ('nokRelation', models.CharField(max_length=100, null=True)),
                ('nokResidence', models.CharField(max_length=100, null=True)),
                ('deathDate', models.DateField(null=True)),
                ('obNumber', models.CharField(max_length=50, null=True)),
                ('notes', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('billStatus', models.CharField(max_length=50, null=True)),
                ('hospitalNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
