# Generated by Django 4.1.1 on 2022-12-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='hist_doctor_notes',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
