# Generated by Django 4.1.1 on 2023-01-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0016_rename_hospno_patientbiodata_op_number'),
        ('consultation', '0004_consultation_visitnoip_consultation_visitnoop'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialconsult',
            name='visitNoIp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit'),
        ),
        migrations.AddField(
            model_name='specialconsult',
            name='visitNoOp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits'),
        ),
    ]
