# Generated by Django 4.1.1 on 2023-01-09 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_specialconsult_visitnoip_specialconsult_visitnoop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='visitNoIp',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='visitNoOp',
        ),
        migrations.RemoveField(
            model_name='specialconsult',
            name='visitNoIp',
        ),
        migrations.RemoveField(
            model_name='specialconsult',
            name='visitNoOp',
        ),
    ]
