# Generated by Django 4.1.1 on 2023-01-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0006_remove_consultation_visitnoip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicbook',
            name='record_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicbook',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
