# Generated by Django 4.1.1 on 2023-02-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0007_clinicbook_record_by_alter_clinicbook_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
