# Generated by Django 4.1.1 on 2023-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0008_prescription_price_alter_prescription_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
