# Generated by Django 4.1.1 on 2023-03-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0020_opvisits_invoice_no'),
        ('consultation', '0010_alter_disease_disease_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='status',
            new_name='visit_status',
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit_no_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.ipvisit'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='visit_no_op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits'),
        ),
    ]
