# Generated by Django 4.1.1 on 2023-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0011_rename_status_consultation_visit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='continuation_notes',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
