# Generated by Django 4.1.1 on 2023-05-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0012_consultation_continuation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialconsult',
            name='service',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
