# Generated by Django 4.1.1 on 2023-05-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0013_specialconsult_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='cons_leave_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='specialconsult',
            name='cons_leave_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='cons_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='specialconsult',
            name='cons_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
