# Generated by Django 4.1.1 on 2023-05-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0014_consultation_cons_leave_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreferral',
            name='referralNotes',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
