# Generated by Django 4.1.1 on 2023-05-29 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0023_opclinics_clinic_type_alter_opclinics_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0015_patientreferral_referralnotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTheater',
            fields=[
                ('reffno', models.AutoField(primary_key=True, serialize=False)),
                ('bookType', models.CharField(choices=[('Elective', 'Elective'), ('Emergency', 'Emergency')], max_length=20, null=True)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('bookNotes', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('receive_date', models.DateTimeField(null=True)),
                ('theaterName', models.CharField(max_length=50, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bkaddedby', to=settings.AUTH_USER_MODEL)),
                ('patient_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.services')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bkreceivedby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
