# Generated by Django 4.1.1 on 2023-05-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0016_booktheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktheater',
            name='schedule_date',
            field=models.DateTimeField(null=True),
        ),
    ]
