# Generated by Django 4.1.1 on 2023-06-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0018_deathcause'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathNotification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('hospitalNo', models.CharField(max_length=100, null=True)),
                ('deceasedName', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('broughtByFullname', models.CharField(max_length=100, null=True)),
                ('broughtByPhone', models.CharField(max_length=100, null=True)),
                ('broughtByIdno', models.CharField(max_length=100, null=True)),
                ('broughtByRelation', models.CharField(max_length=100, null=True)),
                ('nokFullname', models.CharField(max_length=100, null=True)),
                ('nokPhone', models.CharField(max_length=100, null=True)),
                ('nokIdno', models.CharField(max_length=100, null=True)),
                ('nokRelation', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
                ('clinicalNotes', models.CharField(max_length=250, null=True)),
                ('sheetNo', models.CharField(max_length=30, null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('policeStaion', models.CharField(max_length=50, null=True)),
                ('cause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.deathcause')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
