# Generated by Django 4.1.1 on 2023-07-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0019_deathnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TbIndicators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('indicator', models.CharField(max_length=100, null=True)),
                ('lower_age', models.FloatField(null=True)),
                ('upper_age', models.FloatField(null=True)),
                ('recordBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
