# Generated by Django 4.1.1 on 2023-07-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0020_tbindicators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbindicators',
            name='lower_age',
        ),
        migrations.RemoveField(
            model_name='tbindicators',
            name='upper_age',
        ),
        migrations.AddField(
            model_name='tbindicators',
            name='age_category',
            field=models.CharField(choices=[('below 5', 'below 5'), ('above 5', 'above 5'), ('both', 'both')], max_length=50, null=True),
        ),
    ]
