# Generated by Django 4.1.1 on 2023-07-27 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalRecords', '0037_schemes_limit_per_visit'),
        ('consultation', '0021_remove_tbindicators_lower_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='chief_complain',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='TbScreening',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('screenDate', models.DateField(auto_now_add=True)),
                ('screenTime', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('comments', models.CharField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consultation.tbindicators')),
                ('opNumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata')),
                ('visitId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.opvisits')),
            ],
        ),
    ]
