# Generated by Django 4.1.1 on 2022-12-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0002_opvisits_urgency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbill',
            name='op_number',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='service',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='patientbill',
            name='visitNo',
        ),
        migrations.DeleteModel(
            name='cashDeposit',
        ),
    ]
