# Generated by Django 4.1.1 on 2022-12-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0003_remove_patientbill_op_number_and_more'),
        ('laboratory', '0006_alter_labmisstest_request_reff_no_and_more'),
        ('radiology', '0002_alter_exammiss_request_reff_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientBill',
        ),
    ]
