# Generated by Django 4.1.1 on 2022-12-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0004_delete_patientbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='expiryDate',
            field=models.DateField(null=True),
        ),
    ]
