# Generated by Django 4.1.1 on 2022-12-22 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0005_schemes_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime(2022, 12, 22, 11, 41, 55, 368057)),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='paymode',
            field=models.CharField(choices=[('Rebate', 'Rebate'), ('Prepaid', 'Prepaid')], max_length=100),
        ),
    ]
