# Generated by Django 4.1.1 on 2022-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0006_schemes_datecreated_alter_schemes_paymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemes',
            name='dateCreated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
