# Generated by Django 4.1.1 on 2022-12-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0007_alter_schemes_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvisit',
            name='ipNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientbiodata'),
        ),
        migrations.DeleteModel(
            name='IpPatient',
        ),
    ]
