# Generated by Django 4.1.1 on 2022-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0009_theatre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='capacity',
            field=models.FloatField(null=True),
        ),
    ]
