# Generated by Django 4.1.1 on 2023-01-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_substoreitem_batchno'),
        ('MedicalRecords', '0011_services_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.druggeneralitem'),
        ),
    ]
