# Generated by Django 4.1.1 on 2023-01-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0013_alter_services_date_added_alter_services_status'),
    ]

    operations = [
    ]
