# Generated by Django 4.1.1 on 2023-01-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0015_rename_op_number_patientbiodata_hospno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbiodata',
            old_name='hospNo',
            new_name='op_number',
        ),
    ]
