# Generated by Django 4.1.1 on 2023-01-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0016_rename_hospno_patientbiodata_op_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvisit',
            name='admStatus',
            field=models.CharField(default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='admissionType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='fileNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='memberNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='paymode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='visitType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='opvisits',
            name='mchNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opvisits',
            name='memberNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opvisits',
            name='paymode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='opvisits',
            name='visit_type',
            field=models.CharField(max_length=20),
        ),
    ]
