# Generated by Django 4.1.1 on 2023-01-21 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalRecords', '0017_alter_ipvisit_admstatus_alter_ipvisit_admissiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipvisit',
            name='dischargeBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dichby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipvisit',
            name='dischargeDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ipvisit',
            name='dischargeTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ipvisit',
            name='admittedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admby', to=settings.AUTH_USER_MODEL),
        ),
    ]
