# Generated by Django 4.1.1 on 2023-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0018_ipvisit_dischargeby_ipvisit_dischargedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipvisit',
            name='DischargeStatus',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
