# Generated by Django 4.1.1 on 2023-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0020_opvisits_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvisit',
            name='admStatus',
            field=models.CharField(default='active', max_length=20, null=True),
        ),
    ]
