# Generated by Django 4.1.1 on 2023-04-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MedicalRecords', '0021_alter_ipvisit_admstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialClinic',
            fields=[
                ('clinic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clinicName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
