# Generated by Django 4.1.1 on 2023-05-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0022_specialclinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='opclinics',
            name='clinic_type',
            field=models.CharField(choices=[('General', 'General'), ('Special', 'Special')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='opclinics',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
