# Generated by Django 4.1.1 on 2023-05-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0023_opclinics_clinic_type_alter_opclinics_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='wlknumber',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('wlkno', models.IntegerField(null=True)),
            ],
        ),
    ]
