# Generated by Django 4.1.1 on 2023-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0025_wlkpatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wlkpatient',
            name='wlkno',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientbiodata',
            name='trans_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
