# Generated by Django 4.1.1 on 2023-06-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0026_alter_wlkpatient_wlkno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbiodata',
            name='trans_no',
            field=models.CharField(max_length=100, null=True),
        ),      
    ]
