# Generated by Django 4.1.1 on 2023-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0027_patientbiodata_trans_no_and_more'),
    ]

    operations = [        
        migrations.AddField(
            model_name='patientbiodata',
            name='patient_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientbiodata',
            name='op_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
