# Generated by Django 4.1.1 on 2023-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0028_remove_patientbiodata_trans_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbiodata',
            name='patient_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
