# Generated by Django 4.1.1 on 2023-06-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0029_alter_patientbiodata_patient_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbiodata',
            name='trans_no',
        ),
    ]
