# Generated by Django 4.1.1 on 2023-06-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0031_patientbiodata_trans_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbiodata',
            name='patient_no',
        ),
    ]
