# Generated by Django 4.1.1 on 2023-06-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0032_remove_patientbiodata_patient_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbiodata',
            name='patient_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
