# Generated by Django 4.1.1 on 2023-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0033_patientbiodata_patient_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbiodata',
            name='trans_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
