# Generated by Django 4.1.1 on 2023-06-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0035_alter_patientbiodata_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('relCode', models.AutoField(primary_key=True, serialize=False)),
                ('relName', models.CharField(max_length=30)),
            ],
        ),
    ]
