# Generated by Django 4.1.1 on 2023-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0036_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemes',
            name='limit_per_visit',
            field=models.FloatField(null=True),
        ),
    ]
