# Generated by Django 4.1.1 on 2023-09-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0038_alter_ipward_staff_alter_opclinics_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opvisits',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MedicalRecords.patientcategory'),
        ),
    ]
