# Generated by Django 4.1.1 on 2023-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0039_opvisits_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipvisit',
            name='patientCategory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
