# Generated by Django 4.2.6 on 2023-11-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0040_ipvisit_patientcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbiodata',
            old_name='trans_no',
            new_name='trans_num',
        ),
    ]
