# Generated by Django 4.2.6 on 2023-11-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0043_patientbiodata_trans_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='relationship',
            new_name='nokrelation',
        ),
    ]
