# Generated by Django 4.2.6 on 2023-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0044_rename_relationship_nokrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='nok_relation',
            fields=[
                ('relCode', models.AutoField(primary_key=True, serialize=False)),
                ('relName', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='nokrelation',
        ),
    ]
