# Generated by Django 4.2.6 on 2023-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0045_nok_relation_delete_nokrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='relationship',
            fields=[
                ('relCode', models.AutoField(primary_key=True, serialize=False)),
                ('relName', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
