# Generated by Django 4.2.6 on 2023-11-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0046_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nok_relation',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='status',
        ),
    ]
