# Generated by Django 4.1.1 on 2023-11-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0047_delete_nok_relation_remove_relationship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipward',
            name='wardType',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Surgical', 'Surgical'), ('Maternity', 'Maternity')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ipward',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
