# Generated by Django 4.1.1 on 2023-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0048_ipward_wardtype_alter_ipward_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipward',
            name='wardType',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Surgical', 'Surgical'), ('Maternity', 'Maternity'), ('Paediatrics', 'Paediatrics'), ('Eye', 'Eye'), ('NBU', 'NBU'), ('Orthopaedic', 'Orthopaedic'), ('Isolation', 'Isolation'), ('Amenity', 'Amenity'), ('Psychiatry', 'Psychiatry'), ('Obst/Gyn', 'Obst/Gyn'), ('Others', 'Others')], max_length=30, null=True),
        ),
    ]
