# Generated by Django 4.1.1 on 2023-01-09 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sysadmin', '0003_facdepartment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deptReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField(auto_now_add=True, null=True)),
                ('reportName', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('createby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('departmentName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sysadmin.facdepartment')),
            ],
        ),
    ]
